---
- hosts: devils-group
  user: test
  sudo: yes 
  tasks:
  - name: stop tomcat
    command: nohup /usr/local/tomcat/apache-tomcat-7.0.85/bin/catalina.sh stop
  - name: copying war file
    copy: src=/opt/test/WebProject.war
          dest=/usr/local/tomcat/apache-tomcat-7.0.85/webapps/
  - name: start tomcat
    command: nohup /usr/local/tomcat/apache-tomcat-7.0.85/bin/catalina.sh start 
