---
- hosts: server2.sf.com
  user: test
  sudo: yes
  connection: ssh
  tasks:
  - name: installing httpd package
    yum: name=httpd state=installed
  - name: copying index file
    copy: src=index.html dest=/var/www/html/index.html
    notify: starting httpd service
  handlers:
  - name: starting httpd service
    service: name=httpd state=restarted
 
