---
- hosts: server2.sf.com
  user: test
  sudo: yes
  connection: ssh
  tasks:
  - name: installing httpd package
    yum: name=httpd state=installed
    tags:
       - install
  - name: copying index file
    copy: src=index.html dest=/var/www/html/index.html mode=0777
    tags: 
       - copy
  - name: starting httpd service
    service: name=httpd state=restarted
    tags:
       - restart
 
